# Generated by Django 4.0.5 on 2022-06-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbro', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='main_nurse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medbro.xamshira'),
        ),
    ]
