# Generated by Django 4.0.5 on 2022-06-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_xamshira_paid'),
        ('medbro', '0003_alter_hospitals_main_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='xamshira',
            name='kasb',
        ),
        migrations.RemoveField(
            model_name='xamshira',
            name='shifoxona',
        ),
        migrations.RemoveField(
            model_name='xamshira',
            name='user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='to_users',
            field=models.ManyToManyField(related_name='xamshiras', to='user.xamshira'),
        ),
        migrations.AlterField(
            model_name='check_time',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='user.xamshira'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='xamshira',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='del_xamshira', to='user.xamshira'),
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Xamshira',
        ),
    ]
