# Generated by Django 4.0.5 on 2022-06-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cridit_card',
            new_name='credit_card',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Akimov Sarvar', max_length=450),
        ),
    ]
