# Generated by Django 4.0.5 on 2022-06-04 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_cridit_card_user_credit_card_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('longitud', models.CharField(max_length=150)),
                ('latitud', models.CharField(max_length=150)),
                ('credit_card', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Xamshira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('passport', models.FileField(upload_to='pasports')),
                ('minut_10', models.BigIntegerField()),
                ('minut_20', models.BigIntegerField()),
                ('kasb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='user.occupation')),
                ('shifoxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='user.hospitals')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hospitals',
            name='main_nurse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.xamshira'),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='tez_yordam',
            field=models.ManyToManyField(blank=True, related_name='ambulance', to='user.xamshira'),
        ),
    ]
