# Generated by Django 4.0.5 on 2022-06-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_hospitals_occupation_xamshira_hospitals_main_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xamshira',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='pasports'),
        ),
    ]
