# Generated by Django 4.0.5 on 2022-06-04 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_post_maqolas_delete_post_maqola'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_maqolas',
            name='liked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
