# Generated by Django 4.0.5 on 2022-06-04 09:54

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_post_maqolas_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_maqolas',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post_maqolas',
            name='img',
        ),
        migrations.RemoveField(
            model_name='post_maqolas',
            name='name',
        ),
        migrations.AddField(
            model_name='post_maqolas',
            name='quil',
            field=django_quill.fields.QuillField(default='hello'),
            preserve_default=False,
        ),
    ]
