# Generated by Django 4.0.5 on 2022-06-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_post_maqolas_content_remove_post_maqolas_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_maqolas',
            name='name',
            field=models.CharField(default='dsd', max_length=150),
            preserve_default=False,
        ),
    ]
