# Generated by Django 4.0.5 on 2022-06-04 12:48

from django.conf import settings
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_post_maqolas_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kassallik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Post_tabletkas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('quil', django_quill.fields.QuillField()),
                ('kasalik', models.ManyToManyField(to='user.kassallik')),
                ('liked', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
