# Generated by Django 4.0.5 on 2022-06-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_post_maqolas_photo_post_tabletkas_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_maqolas',
            old_name='photo',
            new_name='photos',
        ),
    ]
