# Generated by Django 4.0.5 on 2022-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_photo_post_maqolas_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank='True', upload_to='media'),
        ),
    ]
